project_id = "qflkgtejwqudtceszguf"

[functions.calcular-tiempo-venta-ia]
verify_jwt = false

[functions.extractor-vehiculos]
verify_jwt = false

[functions.normalizar-datos]
verify_jwt = false

[functions.detectar-duplicados]
verify_jwt = false

[functions.prueba-extraccion]
verify_jwt = false

[functions.corregir-precios]
verify_jwt = false

[functions.extraccion-masiva]
verify_jwt = false

[functions.extraccion-completa]
verify_jwt = false

[functions.diagnostico-ml]
verify_jwt = false

[functions.extraccion-masiva-completa]
verify_jwt = false

[functions.extraccion-simple-funcional]
verify_jwt = false

[functions.extraccion-directa-ml]
verify_jwt = false

[functions.enviar-credenciales]
verify_jwt = true

[functions.crear-credenciales]
verify_jwt = true
